Repository scissor-project/open-scissor, pull requests merged in 2018-04, with the labels that each got.

#62 updated d-streamon, updated libssl-dev, fixed d-streamon errors
  docker/d-streamon-master/Dockerfile
  docker/d-streamon-master/d-streamon/.gitignore
  docker/d-streamon-master/d-streamon/lib/app.js
  docker/d-streamon-master/d-streamon/lib/zmqProxy.js
  docker/d-streamon-master/d-streamon/package.json
  docker/d-streamon-master/d-streamon/streamon/CMakeCache_old.txt
  docker/d-streamon-master/d-streamon/streamon/config/modbus_device_scan.xml
  docker/d-streamon-master/d-streamon/streamon/config/modbus_dos.xml
  docker/d-streamon-master/d-streamon/streamon/config/modbus_function_scan.xml
  docker/d-streamon-master/d-streamon/streamon/config/new_old/modbus_dos-2.xml
  docker/d-streamon-master/d-streamon/streamon/config/new_old/modbus_ip_scan.xml
  docker/d-streamon-master/d-streamon/streamon/config/tmp/.gitignore
  docker/d-streamon-master/d-streamon/streamon/config/traces/modbus_device_scan.pcap
  docker/d-streamon-master/d-streamon/streamon/config/traces/modbus_dos-1.pcap
  docker/d-streamon-master/d-streamon/streamon/config/traces/modbus_dos-2.pcap
  docker/d-streamon-master/d-streamon/streamon/config/traces/modbus_function_scan.pcap
  docker/d-streamon-master/d-streamon/streamon/config/traces/utils/setAndGoPcap.sh
  docker/d-streamon-master/d-streamon/streamon/scripts/event.py~
  docker/d-streamon-master/d-streamon/streamon/scripts/messages.xml~
  docker/d-streamon-master/d-streamon/streamon/scripts/moin.py~
  docker/d-streamon-master/d-streamon/streamon/start.sh
  docker/d-streamon-master/d-streamon/sys/install.sh
Labels: bug, enhancement

#63 fixed login, add ssh inside dockerfile
  docker/d-streamon-master/Dockerfile
  docker/d-streamon-master/d-streamon/README.md
  docker/d-streamon-master/d-streamon/lib/routes/index.js
  docker/d-streamon-master/d-streamon/lib/scripts/pullGit.sh
  docker/d-streamon-master/d-streamon/lib/views/layout.jade
  docker/d-streamon-master/d-streamon/public/js/controllers/auth/login.js
  docker/d-streamon-master/d-streamon/public/js/services/user.js
  docker/d-streamon-master/d-streamon/sys/install.sh
  docker/d-streamon-slave/Dockerfile
  docker/d-streamon-slave/start-d-streamon-slave.sh
  install.sh
Labels: bug

#73 Fix event-correlator setuptools installation
  docker/event-correlator/Dockerfile
Labels: bug

#75 Added Raw Data Analyzer to Open Scissor
  .travis.yml
  docker/docker-compose.yml
  docker/raw-data-analyzer/Dockerfile
  docker/raw-data-analyzer/converter-config/converter.conf
  docker/raw-data-analyzer/keys/RPM-GPG-KEY-Prelude-IDS
  docker/raw-data-analyzer/keys/assystem-prelude.raw
  docker/raw-data-analyzer/start-raw-data-analyzer.sh
  docker/raw-data-analyzer/yum-config/epel.repo
  docker/raw-data-analyzer/yum-config/release.prelude-siem.com_assystem_pkgs_centos_7_.repo
  docker/raw-data-analyzer/yum-config/scissor.repo
  test/inspec/docker/raw-data-analyzer/controls/raw-data-analyzer.rb
  test/inspec/docker/raw-data-analyzer/inspec.yml
Labels: enhancement

#77 Fixed wrong kafka ip in raw-data-analyzer configuration
  docker/raw-data-analyzer/converter-config/converter.conf
Labels: bug

#79 Fixed wrong startup conf
  docker/raw-data-analyzer/start-raw-data-analyzer.sh
Labels: bug
